version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${PGNAME}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASS}
    env_file:
      - .env
  web:
    image: climatefarmers/farmdb:latest
    build: 
        context: .
        dockerfile: ./farmdb.Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./src:/code
    depends_on:
      - db
    env_file:
      - .env

