apiVersion: apps/v1
kind: Deployment
metadata:
  name: farmdb-django-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: farmdb-django-deployment
  template:
    metadata:
      labels:
        app: farmdb-django-deployment
    spec:
      containers:
      - name: farmdb-django
        image: climatefarmers/farmdb-django
        command: ['sh']
        args: ['entrypoint.sh']
        imagePullPolicy: Always
        env:
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: PGPASS
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: PGNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: database
        - name: PGHOST
          value: "10.31.128.5"
        - name: PGPORT
          value: "5432"
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: django_secret_key
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: google_api_key
        - name: TYPEFORM_SECRET
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: typeform_secret
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP

      - name: address-parser
        image: climatefarmers/address-parser
        imagePullPolicy: Always
        
