apiVersion: apps/v1
kind: Deployment
metadata:
  name: farmdb-django-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: farmdb-django-deployment
  template:
    metadata:
      labels:
        app: farmdb-django-deployment
    spec:
      containers:
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.17
        command:
          - "/cloud_sql_proxy"
          - "-ip_address_types=PRIVATE"
          - "-instances=idyllic-silicon-318213:europe-west3:cfcommon-pgfarmdb-dev=tcp:5432"
        securityContext:
          runAsNonRoot: true

      - name: farmdb-django
        image: climatefarmers/farmdb-django
        command: ['python ']
        args: ['manage.py', 'runserver', '0.0.0.0:8000']
        imagePullPolicy: Always
        env:
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: PGPASS
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: PGNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: database
        - name: PGHOST
          value: "127.0.0.1"
        - name: PGPORT
          value: 5432"
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: django_secret_key
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: google_api_key
        - name: TYPEFORM_SECRET
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: typeform_secret
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        
