apiVersion: apps/v1
kind: Deployment
metadata:
  name: soil-monitoring-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soil-monitoring-deployment
  template:
    metadata:
      labels:
        app: soil-monitoring-deployment
    spec:
      containers:
      - name: soil-monitoring
        image: climatefarmers/soil-monitoring:sha-614b5e3
        resources:
          limits:
            memory: "500Mi"
          requests:
            memory: "250Mi"
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP