name: Farmdb build and publish

env:
  IMAGE_NAME: climatefarmers/farmdb-django
  PATH: ./apps/farmdb-django

on:
  schedule:
    - cron: '00 03 * * *'
  push:
    branches: [ main ]
    paths:
      - ${{ env.PATH }}/**
      - .github/workflows/publish-farmdb-django.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: climatefarmers
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          repository: ${{ env.IMAGE_NAME }}
          context: ${{ env.PATH }}
          file: farmdb.Dockerfile
          tags: latest